# docker run --restart always -d \
#     -p 8021:8021 \
#     --name couch-web-rtc-signaling \
#     ghcr.io/vincentkerdraon/couch-web-rtc-signaling:latest

# Dockerfile for couch-web-rtc-signaling
FROM node:22-alpine
WORKDIR /usr/src/app
COPY server-signaling.js ./
RUN npm install ws
CMD ["node", "server-signaling.js"]
