# This workflow builds and pushes Docker images to GitHub Container Registry (ghcr.io)
# using the automatically provided GITHUB_TOKEN for authentication.

name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
      - video_stream_test

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build_signaling:
    name: Build and Push Signaling Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push signaling image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_signaling
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/couch-web-rtc-signaling:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/couch-web-rtc-signaling:${{ github.sha }}

  build_ssr:
    name: Build and Push Angular SSR App Image
    runs-on: ubuntu-latest
    needs: build_signaling
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push SSR image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: BASE_HREF=/couch-web-rtc/
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/couch-web-rtc-ssr:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/couch-web-rtc-ssr:${{ github.sha }}
